parser:
  - changed-files:
      - any-glob-to-any-file: 'packages/core/**'
lsp:
  - changed-files:
      - any-glob-to-any-file: 'packages/server/**'
extension:
  - changed-files:
      - any-glob-to-any-file: 'packages/extension/**'
docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
